### PR TITLE
add LV2 plugin target

### PR DESCRIPTION
**Pull request by dromer**
I don't know if the CI is 100% correct so it will likely need some tweaks :)

### CODE REVIEW

**Comment by dan-german** [comment]
lgtm!

**Comment by dan-german** [comment]
https://github.com/dan-german/blocks/actions

works only for windows. do you want to look into it or should i just revert the changes for the rest of the targets for now?

**Comment by dromer** [comment]
Well I wouldn't have merged it just like that :#

I don't understand why the Linux build fails, but on macOS it's something to do with codesigning which I've never done.

On my machine the Linux build succeeds, will try to follow the exact CI steps and see if I can reproduce ..

**Comment by dan-german** [comment]
you’re right i just didn’t want to be bothered figuring out how to run the actions on a forked pr 😅
straightforward changes so no biggy!

**Comment by dromer** [comment]
Hmm, the Linux build seems to be an issue with the LTO linker. I can reproduce it with a Release build locally, even though a standard build succeeded just fine.

We may need someone better versed in such builds to take a look at this ..

**Comment by dan-german** [comment]
reverted all but windows. 
most of the users are on windows, so this is still an impactful contribution. 
thanks!

**Comment by dromer** [comment]
For the macOS code signing you probably just need to sign the individual bundle files.
For Linux I'm asking around if someone knows what's going on in the LTO build.

**Pull request merged**
